### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by InimiAlt**

### CODE REVIEW

**Comment by 1RB** [comment]
BOOM HERE

**Comment by InimiAlt** [comment]
i closed the console again

**Comment by 1RB** [comment]
🤖

**Review by LimitlyAI — APPROVED** [review]
Hey! Thanks for your pull request! Your commit(s) have been verified and have been merged! Thanks for being awesome <3

**Comment by 1RB** [comment]
o-

**Comment by InimiAlt** [comment]
:o

**Comment by 1RB** [comment]
zat waz sik

**Comment by InimiAlt** [comment]
didnt get an invite tho

**Comment by InimiAlt** [comment]
oh fuck

**Comment by InimiAlt** [comment]
i forgot to do "not" on one, so the value is flipped

**Comment by 1RB** [comment]
o:

**Comment by 1RB** [comment]
still sik

**Pull request merged**
