### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Alternimi**

### CODE REVIEW

**Review by LimitlyAI — CHANGES_REQUESTED** [review]
Thanks for your pull request! Before I merge your pull request to give you collaborator, I want some changes, here are they:<br><br>   -  - <i>Invalid file, you've recently changed your username, you can only put files in your [old usernames' folder](/Contributors/InimiAlt/). As soon as you do that, we will automatically rename your folder to your new username. (if we do it now it will break this pull request)</i>

**Review by LimitlyAI — CHANGES_REQUESTED** [review]
Thanks for your pull request! Before I merge your pull request to give you collaborator, I want some changes, here are they:<br><br>   -  - <i>Invalid file, you've recently changed your username, you can only put files in your [old usernames' folder](/Contributors/InimiAlt/). As soon as you do that, we will automatically rename your folder to your new username. (if we do it now it will break this pull request)</i>

**Comment by LimitlyAI** [comment]
Thanks for your pull request! Before I merge your pull request to give you collaborator, I want some changes, here are they:<br><br>   - `/Contributors/Alternimi/README.md` - <i>Invalid file, you've recently changed your username, you can only put files in your [old usernames' folder](/Contributors/InimiAlt/). As soon as you do that, we will automatically rename your folder to your new username. (if we do it now it will break this pull request)</i>

**Review by LimitlyAI — APPROVED** [review]
<h1>:tada: Your pull request has been approved! :tada:</h1><p>Hey! Welcome to the family <b>@Alternimi</b>! Your pull request has been approved! :sparkles:<br>This means that you should get a collaborator invite to your email shortly! Meanwhile, let me tell you what is gonna happen next!</p>

**Comment by LimitlyAI** [comment]
Hey there @Alternimi<br><br>We're here to let you know that we have successfully renamed your old username's folder to your new username.<br><br><br>❤️ -Limitly

**Comment by InimiAlt** [comment]
Hey there @InimiAlt!

We're here to let you know that we have successfully renamed your old username's folder to your new username.

When you change your username, The AI gets a little confused and renames the folder (like we just did! 🎉). Sadly that breaks the history of the folder and the files inside it.
This means that we can't check when the last time it was you committed, so we're sad to say that you we have to temporarily remove you as a collaborator (nothing personal!).
Now don't fret! It's super easy to get it back! Just update a file in your newly renamed folder, and the AI will approve your pull request, and an invite will be sent!

❤️ -Limitly

**Pull request merged**
